spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_erp
    username: erp_admin
    password: erp_admin_password

school-erp:
  security:
    permission-scan-package: org.example.schoolerp
    secret-key: very-secure-development-mode-only-key
    access-token-expiration: 1200000

logging:
  level:
    '[org.example.schoolerp]': debug
    '[org.hibernate.sql]': debug

