spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    '[org.example.schoolerp]': info
    '[org.hibernate.sql]': warn

management:
  endpoint:
    health:
      show-details: never