spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_erp
    username: erp_admin
    password: erp_admin_password
  flyway:
    validate-migration-naming: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always


school-erp:
  security:
    permission-scan-package: org.example.schoolerp
    secret-key: very-secure-development-mode-only-key
    access-token-expiration: 1200000

logging:
  level:
    '[org.hibernate]': warn
    '[org.apache.tomcat]': warn
    '[org.apache.catalina]': warn
    '[org.springframework]': warn
    '[com.zaxxer.hikari]': warn

    '[org.example.schoolerp]': debug
    '[org.springframework.security]': debug
    '[org.flywaydb]': info


  pattern:
    console: "%d{HH:mm:ss} %highlight(%-5level) [%X{correlationId}] %cyan([%logger{0}]) - %msg%n"

    # org.hibernate.SQL: DEBUG
    # org.hibernate.sql.exec: DEBUG
    # org.hibernate.orm.jdbc.bind: TRACE
    # org.hibernate.orm.jdbc.extract: TRACE
