spring:
  profiles:
    active: dev
  application:
    name: schoolErp
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers
  endpoint:
    health:
      show-details: always
# logging:
#   pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"