spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_erp
    username: erp_admin
    password: erp_admin_password

school-erp:
  security:
    permission-scan-package: org.example.schoolerp

logging:
  level:
    '[org.example.schoolerp]': debug
    '[org.hibernate.sql]': debug

